dataset: online

# ROS 1 特定配置 (新增)
ros:
  map_frame: world        # 对应 launch 中的 odom_frame (use_gt_frame=true 时为 world)
  camera_frame: left_cam  # 对应 launch 中的 sensor_frame (use_gt_frame=true 时为 left_cam)

data:
  datadir: /online/
  start: 0 
  output_dir: ./results
  gap: 25


cam:
  H: 480
  W: 720
  fx: 415.692
  fy: 415.692
  cx: 360.0
  cy: 240.0
  png_depth_scale: 1

detection:
  score_thresh: 0.35 #0.4 #0.25
  uv_bound: True
  uv_bound_value: 0.9
  floor_mask: True #False
  floor_ratio: 15
  scale_box: 1.5

association:
  small_threshold: 0.1 #0.2
  rotation_gap: 30 #30
  translation_gap: 0.8 #1.0 #0.8 #0.5 #0.5 best #1.0 #0.1


box_fusion:
  use: True 
  iters: 20 
  pst_path: ./data/pst_1024_0.tiff
  pst_size: 1024
  random_opt:
    center_init_size: 0.1 
    center_scaling_coefficient:  0.1
    shape_init_size: 0.5
    shape_scaling_coefficient: 0.5 
  check_valid: False
  nms_threshold: 0.1 
  small_size: 0.35


vis:
  rerun: False 
  show_class: False 
  show_label: False 
  trajectory: True

eval: False